name: Linting and Tests

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          $CONDA/bin/python --version
          conda env update --file environment.yaml --name base
          $CONDA/bin/python -m pip list
          $CONDA/bin/python --version
      - name: Lint
        run: |
          pre-commit run --all
      - name: Test with pytest
        run: |
          $CONDA/bin/pytest --junitxml=report.xml -v -s --no-cov-on-fail --cov=.
          $CONDA/bin/flake8 . --exit-zero --output-file=flake8.txt
          $CONDA/bin/coverage xml  --omit "val02_counters/*"
      - name: Archive junit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit
          path: report.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: cobertura
          path: coverage.xml
      - name: Archive flake8 code style results
        uses: actions/upload-artifact@v3
        with:
          name: flake8
          path: flake8.txt
